FtmDjango/FtmDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('posts.urls')),
]

FtmDjango/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name="posts-index"),
    path('<int:received_id>/details/', views.details, name="posts-details"),
]

FtmDjango/posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    
    title = models.CharField(max_length = 200)
    body = models.TextField()
    created_at = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

FtmDjango/posts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post

# Create your views here.

def index(request):
    
    return render(request, 'posts/index.html',{'posts':Post.objects.all()})

def details(request,received_id):
	post = get_object_or_404(Post, pk=received_id)
	return render(request, 'posts/details.html',{'post':post})

FtmDjango/posts/templates/posts/details.html
{% extends 'posts/layout.html' %}

{% block content %}
							<!-- Display Post Title -->
<h3 class="center-align red lighten-3">{{post.title}}</h3>
<div class="card">
  <div class="card-content">
    <!-- Post Body-->
	<p class="article-content">{{ post.body }}</p>
  </div>
  <div class="card-action">
    <!-- Post Date-->
	<small class="text-muted">{{ post.created_at }}</small>
  </div>
</div>
<a href="/" class="btn">Go Back</a>
{% endblock %}

FtmDjango/posts/templates/posts/index.html
{% extends 'posts/layout.html' %}

{% block content %}    
										<!-- Display the Page Title Latest Post -->
<h3 class="center-align red lighten-3">Latest Post</h3>
<ul class="collection">
    <!-- Retrieve all the post from database-->	
	<!-- -->
	{% for post in posts %}						<!-- Display the post title -->
    <li class="collection-item"><a href="{% url 'posts:posts-details' post.id %}">{{ post.title }}</a></li>
	{% endfor %}
    <!-- -->
</ul>
{% endblock %}

FtmDjango/posts/templates/posts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <title>LaSalle College Blog</title>
</head>

<body>
  <header class="container center-align">
    <h1>LaSalle College Blog</h1>
  </header>

  <div class="container">
    {% block content %}
    {% endblock %}
    <br>
												<!-- add the link for admin -->
    <a style="display:block" class="center-align" href="/admin">Admin Login</a>
  </div>
</body>

</html>